---
- hosts: dhcp01-fosc.fosc.local
  become: yes
  tasks:
  - name: Copy dhcpd config to DHCP1
    copy:
      src: ./dhcp1-dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0600'

- hosts: dhcp02-fosc.fosc.local
  become: yes
  tasks:
  - name: Copy dhcpd config to DHCP2
    copy:
      src: ./dhcp2-dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0600'

- hosts: dhcp
  become: yes
  tasks:
  - name: Install/update dhcpd
    yum:
      name: dhcp
      state: latest
  - name: Allow dhcp through firewall
    firewalld:
      service: dhcp
      permanent: yes
      state: enabled
      immediate: yes
  - name: Allow dhcp peer communication (failover) through firewall
    firewalld:
      port: 647/tcp
      permanent: yes
      state: enabled
      immediate: yes
  - name: Start dhcpd service
    service:
      name: dhcpd
      state: started
