---
- hosts: dhcp1.fosc.local
  tasks:
  - name: Copy dhcpd config to DHCP1
    copy:
      src: ./dhcp1-dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0600'

- hosts: dhcp2.fosc.local
  tasks:
  - name: Copy dhcpd config to DHCP2
    copy:
      src: ./dhcp2-dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0600'

- hosts: dhcp
  tasks:
  - name: Install/update dhcpd
    yum:
      name: dhcpd
      state: latest
   - name: Start dhcpd service
     service:
       name: dhcpd
       state: started
