---
- name: Configure Apache on util
  hosts: util-fosc
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Allow http through firewall
      firewalld:
        service: http
        state: enabled
        permanent: true

    - name: Restart the firewall
      service:
        name: firewalld
        state: restarted

    - name: Start Apache service
      service:
        name: httpd
        state: started
